services:
  azureblobstoragewebapi:
    image: azureblobstoragewebapi
    build:
      context: .
      dockerfile: AzureBlobStorageWebApi/Dockerfile
      
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azure-blob-storage
    volumes:
      - ./.containers/blob_storage/data:/data
    restart: always
    ports:
      - "10000:10000"

